name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Create API Documentation
        run: |
          nvim --version
          make api_documentation

      - name: Create User Documentation
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: plugin-template
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Generate Tags
        run: |
          nvim -c 'helptags doc' -c 'quit'

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(vimdoc): Auto-generate user / API documentation + vimtags"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
