---
on: [pull_request]
name: lint

jobs:
  type_check:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install llscheck

      - name: Lint
        run: make llscheck
