---
on: [push]
name: lint

jobs:
  typecheck:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neodev # Get neodev and neovim/runtime for builtin types
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: ".dependencies/neodev.nvim"

      - name: Checkout Neovim for type annotations
        uses: actions/checkout@v3
        with:
          repository: "neovim/neovim"
          path: ".dependencies/neovim"

      - name: Checkout Busted
        uses: actions/checkout@v3
        with:
          repository: LuaCATS/busted
          path: ".dependencies/busted"

      - name: Checkout luassert
        uses: actions/checkout@v3
        with:
          repository: LuaCATS/luassert
          path: ".dependencies/luassert"

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
        with:
          configpath: ".github/workflows/.luarc.json"
          directories: |
           lua
           plugin
           scripts
           spec
