name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: stable

    - name: build
      run: |
        luarocks install busted
        luarocks install nlua
        luarocks install nui.nvim
        luarocks make

    - name: test
      run: |
        make test
