---
on: [push, pull_request]
name: test

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [v0.9.0, v0.10.0, nightly, stable]
    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"
    steps:
    - name: Checkout plugin-template
      uses: actions/checkout@v4
      with:
        repository: ColinKennedy/nvim-best-practices-plugin-template
        path: neovim_plugin
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}
    - name: Run tests
      working-directory: ./neovim_plugin
      run: |
        nvim --version
        make test
