name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim: [stable]

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim ${{ matrix.neovim }}"

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit" # Neovim is compiled with LuaJIT so we might as well match.

    - uses: leafo/gh-actions-luarocks@v4

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    - name: build
      run: |
        luarocks install busted
        luarocks install nlua
        luarocks install nui.nvim
        luarocks make

    - name: test
      run: |
        make test
