name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - add_windows_tests

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [v0.10.0, stable, nightly]

        include:
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "v0.10.0"
        - os: "windows-latest"
          toolchain: "mingw"  # unused, other than for display in the UI
          luaVersion: "luajit"
          neovim: "v0.10.0"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup MSVC
      # the 'hishamhm/gh-actions-lua' step requires msvc to build PuC Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Lua
      uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "${{ matrix.luaVersion }}"

    - name: Install Luarocks
      uses: luarocks/gh-actions-luarocks@v5

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    # We need this hack until a better solution is available.
    #
    # Reference: https://github.com/nvim-neorocks/luarocks-tag-release/issues/435
    #
    - name: Expand The Template Rockspec
      uses: ColinKennedy/luarocks-rockspec-expander@v1.0.0
      with:
        input: template.rockspec
        output: nvim-best-practices-plugin-template-scm-1.rockspec
        delete_input_after: true

    - name: Build Test Dependencies
      run: |
        luarocks test nvim-best-practices-plugin-template-scm-1.rockspec --prepare

    - name: Test
      run: |
        luarocks test --test-type busted
