---
# TODO:: Revert this later
# on: [pull_request]
on:
  push:
    branches:
      - lint_test
name: test

jobs:
  test_unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [v0.9.0, v0.10.0, nightly, stable]
    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"
    steps:
    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4
    - name: Install Busted
      run: |
        luarocks install busted
    - name: Checkout plugin-template
      uses: actions/checkout@v4
      with:
        repository: ColinKennedy/nvim-best-practices-plugin-template
        path: neovim_plugin
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}
    - name: Run tests
      working-directory: ./neovim_plugin
      run: |
        nvim --version
        eval $(luarocks path --lua-version 5.1 --bin)
        busted --helper spec/minimal_init.lua .
  # test_windows:
  #   strategy:
  #     matrix:
  #       os: [windows-latest]
  #       neovim: [v0.9.0, v0.10.0, nightly, stable]
  #   runs-on: ${{ matrix.os }}
  #   name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"
  #   steps:
  #   - name: Checkout plugin-template
  #     uses: actions/checkout@v4
  #     with:
  #       repository: ColinKennedy/nvim-best-practices-plugin-template
  #       path: neovim_plugin
  #   - uses: rhysd/action-setup-vim@v1
  #     with:
  #       neovim: true
  #       version: ${{ matrix.neovim }}
  #   - name: Run tests
  #     working-directory: ./neovim_plugin
  #     run: |
  #       nvim --version
  #       luarocks path --lua-version 5.1 --bin > temp.cmd
  #       call temp.cmd
  #       del temp.cmd
  #       busted --helper spec/minimal_init.lua .
