name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - luarocks_prepare_test

jobs:
  test:
    strategy:
      matrix:
        include:
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "v0.10.0"
        - os: "windows-latest"
          toolchain: "mingw"  # unused, other than for display in the UI
          luaVersion: "luajit"
          neovim: "v0.10.0"

    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} ${{ matrix.toolchain }}, Lua ${{ matrix.luaVersion }}, Neovim: ${{ matrix.neovim }}"

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup MSVC
      # the 'luarocks/gh-actions-lua' step requires msvc to build PUC-Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "${{ matrix.luaVersion }}"

    - uses: luarocks/gh-actions-luarocks@v5

    - name: Build Test Dependencies
      run: |
        luarocks test nvim-best-practices-plugin-template-scm-1.rockspec --prepare
