name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [v0.10.0, stable, nightly]

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v10
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "luajit-openresty"

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    # We need this hack until a better solution is available.
    #
    # Reference: https://github.com/nvim-neorocks/luarocks-tag-release/issues/435
    #
    - name: Expand The Template Rockspec
      uses: ColinKennedy/luarocks-rockspec-expander@v1.0.0
      with:
        input: template.rockspec
        output: nvim-best-practices-plugin-template-scm-1.rockspec
        delete_input_after: true

    - name: Build Test Dependencies
      run: |
        luarocks test nvim-best-practices-plugin-template-scm-1.rockspec --prepare

    - name: Test
      run: |
        luarocks test --test-type busted
