name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim: [stable]

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim ${{ matrix.neovim }}"

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        luarocks install busted
        luarocks make

    - name: test
      run: |
        make test
