# TODO: (you) Make sure to update your file_types below to whatever makes sense for you.

name: URLChecker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  urlchecker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: urlcheck - doc directory
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: doc
        file_types: .json,.lua,.md,.txt,.vim,.yml

    - name: urlcheck - lua directory
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: lua
        file_types: .json,.lua,.md,.txt,.vim,.yml

    - name: urlcheck - plugin directory
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: plugin
        file_types: .json,.lua,.md,.txt,.vim,.yml

    - name: urlcheck - scripts directory
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: scripts
        file_types: .json,.lua,.md,.txt,.vim,.yml

    - name: urlcheck - spec directory
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: spec
        file_types: .json,.lua,.md,.txt,.vim,.yml

    - name: urlcheck - CHANGELOG.md
      uses: urlstechie/urlchecker-action@master
      with:
        exclude_patterns: https://github.com/ColinKennedy/nvim-best-practices-plugin-template/compare/v
        subfolder: .
        include_files: CHANGELOG.md
      if: ${{ github.event.pull_request.head.ref == 'release-please--branches--main' }}

    - name: urlcheck - CHANGELOG.md
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: .
        include_files: CHANGELOG.md
      if: ${{ github.event.pull_request.head.ref != 'release-please--branches--main' }}

    - name: urlcheck - README.md
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: .
        include_files: README.md
