# TODO: (you) Make sure to update your file types below to whatever makes sense for you.

name: URLChecker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  urlchecker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install urlchecker
      run: |
        python -m pip install urlchecker

    - name: "Directory: doc"
      run: |
        urlchecker check \
          --branch main \
          --subfolder doc \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "Directory: lua"
      run: |
        urlchecker check \
          --branch main \
          --subfolder lua \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "Directory: plugin"
      run: |
        urlchecker check \
          --branch main \
          --subfolder plugin \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "Directory: scripts"
      run: |
        urlchecker check \
          --branch main \
          --subfolder scripts \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "Directory: spec"
      run: |
        urlchecker check \
          --branch main \
          --subfolder scripts \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "File: CHANGELOG.md"
      if: ${{ github.event.pull_request.head.ref == 'release-please--branches--main' }}
      run: |
        urlchecker check \
          --branch main \
          --subfolder . \
          --exclude-patterns "https://github.com/ColinKennedy/nvim-best-practices-plugin-template/compare/v" \
          --files CHANGELOG.md \
          --no-print \
          --file-types .json,.lua,.md,.txt,.vim,.yml \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "File: CHANGELOG.md"
      if: ${{ github.event.pull_request.head.ref != 'release-please--branches--main' }}
      run: |
        urlchecker check \
          --branch main \
          --subfolder . \
          --files CHANGELOG.md \
          --no-print \
          --retry-count 1 \
          --timeout 5 \
          .

    - name: "File: README.md"
      run: |
        urlchecker check \
          --branch main \
          --subfolder . \
          --files README.md \
          --no-print \
          --retry-count 1 \
          --timeout 5 \
          .
